http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/cards'
  api2:
    host: localhost
    paths: '/addresses/1'
  auth:
    host: localhost
    paths: '/auth'
  basic:
    host: localhost
    paths: '/users/1'
serviceEndpoints:
  httpbin:
    url: 'https://admin.knex.alfierichou.com'
  httpbin2:
    url: 'https://knex.alfierichou.com'
  auth:
    url: 'http://localhost:7000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - customlogger
  - jwt
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - customlogger:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  test:
    apiEndpoints:
      - api2
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      # - key-auth:
      #     - action:
      #         apiKeyHeader: hahahahaha
      #         disableHeadersSchema: true
      - rate-limit:
          - action:
              max: 1
              windowMs: 120000
              rateLimitBy: "${req.hostname}"
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - customlogger:
      - proxy:
          - action:
              serviceEndpoint: httpbin2
              changeOrigin: true
  auth:
    apiEndpoints:
      - auth
    policies:
      - jwt:
          - action:
              secret: 'a093d64d32'
      - proxy:
          - action:
              serviceEndpoint: auth
              changeOrigin: true
  basic:
    apiEndpoints:
      - basic
    policies:
      - key-auth:
          - actions:
              apiKeyHeader: 676NGDhwxjT1TzbL7D0AIA:0IXqzAN2fWTGhPHVkUKJza
              disableHeadersScheme: true
      - proxy:
          - action:
              serviceEndpoint: httpbin2
              changeOrigin: true