# Core
db:
  redis:
    emulate: false
    namespace: EG
    host: '47.106.84.59'
    port: '6379'
    password: 'yangzong'

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  customlogger:
    package: express-gateway-plugin-customlogger
  jwt:
    package: express-gateway-plugin-jwt
    secret: a093d64d32

cli:
  url: http://localhost:9876